### ISSUE TITLE
Suggestion: Temporarily make the glass flask recipe produce filled flasks.

### ISSUE THREAD

**Issue by CupcakeValkyrie** [Tirocupidus/TheExiledRPOverhaul#94] opened 2017-08-25 16:46 UTC
Currently, the only way to get filled flasks is either to melt ice (impossible if you're in the desert) or ask a DM to exchange them. So, I propose two temporary changes until the ability to fill flasks from a water source is fixed.

- Change the glass flask recipe so that it produces already-filled flasks.

- Change the aloe recipe (and any other recipe that requires empty flasks) to require the filled ones instead.

This is temporary until the filling of flasks is fixed.

**Comment by gjpeebles** [comment] 2017-08-25 18:00
This is a duplicate of the very last Issue I created. :P Closing it.

**Closed as completed by gjpeebles** 2017-08-25 18:00 UTC
